Cart in socket
beamkenya/ElixirConfAfrica pull request #32
Opened 2023-10-18 02:09 UTC by MICHAELMUNAVU83

## Notes for the reviewer

I have worked on adding items in the cart using the socket to avoid interacting with the db

## GIF (for features)

https://github.com/beamkenya/ElixirConfAfrica/assets/86654131/05aa311f-3edb-459b-a0fc-ee5e478d93a1

2023-10-18 17:52 UTC, 75pollet requested changes

2023-10-18 17:52 UTC, 75pollet commented on lib/elixir_conf_africa_web/live/home_live/index.ex
> +      |> String.to_integer()
you do not need to convert the id to an integer here. Repo.get will still succeed

2023-10-18 17:52 UTC, 75pollet commented on lib/elixir_conf_africa_web/live/home_live/index.ex
> +       |> put_flash(:error, "Ticket already in cart")}
is this what should happen if the ticket is already added to cart? 🤔  In this scenario shouldn't we increment the quantity of the ticket?

2023-10-18 17:52 UTC, 75pollet commented on lib/elixir_conf_africa_web/live/home_live/index.html.heex
> +      phx-click="change_page_state"
what is this event meant to do? I suggest you name it differently because its a bit confusing

2023-10-23 06:33 UTC, okothkongo requested changes
Let's make the `main` branch our out branch for other branches.
I see this one branching out from `style-home-with-event-and-ticket-details`

2023-10-23 14:02 UTC, MICHAELMUNAVU83 commented
> Let's make the `main` branch our branch out for other branches. I see this one branching out from `style-home-with-event-and-ticket-details`

Hey @okothkongo  , I did this as I needed the material from `style-home-with-event-and-ticket-details` as you hadn't merged it yet

2023-10-23 14:11 UTC, okothkongo commented
> > Let's make the `main` branch our branch out for other branches. I see this one branching out from `style-home-with-event-and-ticket-details`
> 
> Hey @okothkongo , I did this as I needed the material from `style-home-with-event-and-ticket-details` as you hadn't merged it yet

It is my suggestion that we refrain from progressing with work until it has undergone a thorough review and been merged into the main branch. This approach ensures that our codebase consistently meets our quality standards before it becomes a part of the main codebase.

To facilitate this, we could designate a specific task, such as 'style-home-with-event-and-ticket-details,' as a blocker for other work. This way, we have a clear and standardized process for handling code changes.

Maintaining a single source of truth, which in our case is the 'main' branch, is essential to prevent confusion and maintain order within our project. I believe that by adopting this approach, we can enhance collaboration and streamline our development process.

2023-11-15 08:35 UTC, closed without merging